export const actionTypes = {
    // movie
    SET_MOVIES: "SET_MOVIES",
    SET_DETAIL_MOVIE: "SET_DETAIL_MOVIE",
    SET_PAGE: "SET_PAGE",
    SET_BANNER: "SET_BANNER",
    SET_SHOWTIMES: "SET_SHOWTIMES",
    // user
    SET_LOGIN: "SET_LOGIN",
    SET_SIGNIN: "SET_SIGNIN",
    SET_USER: "SET_USER",
    REMOVE_USER: "REMOVE_USER",
    // cinema
    SET_CINEMA: "SET_CINEMA",
    SET_CINEMALIST: "SET_CINEMALIST",
    SET_CUMRAP: "SET_CUMRAP",
    // booking
    SET_MOVIE_ROOM: "SET_MOVIE_ROOM",
    BOOKING_SEAT: "BOOKING_SEAT",
    BOOKING_TICKET: "BOOKING_TICKET",
    OTHER_BOOKING_SEAT: "OTHER_BOOKING_SEAT",
    // layout
    SHOW_LOADING: "SHOW_LOADING",
    HIDDEN_LOADING: "HIDDEN_LOADING",
};
