export const actionTypes = {
    SET_MOVIES: "SET_MOVIES",
    SET_DETAIL_MOVIE: "SET_DETAIL_MOVIE",
    SET_LOGIN: "SET_LOGIN",
    SET_SIGNIN: "SET_SIGNIN",
    SET_USER: "SET_USER",
    SET_PAGE: "SET_PAGE",
    SET_BANNER: "SET_BANNER",
    SET_CINEMAS: "SET_CINEMAS",
    SET_CUMRAP: "SET_CUMRAP",
};
